In [ ]:
#Name: Abhishek Nage
#BE A COBA02 
#HPC ASS 4

In [2]:
USE_GPU = False

if USE_GPU:
    import cupy as xp
else:
    import numpy as xp

# User Input
N = int(input("Enter size of vector/matrix (N): "))

# Input Vectors
print("Enter elements for Vector A:")
A = xp.array([int(input(f"A[{i}]: ")) for i in range(N)])
print("Enter elements for Vector B:")
B = xp.array([int(input(f"B[{i}]: ")) for i in range(N)])

# Vector Addition
C = A + B

print("\nVector A:", A)
print("Vector B:", B)
print("Addition (A + B):", C)

# Input Matrices
print("\nEnter elements for Matrix D:")
D = xp.zeros((N, N), dtype=int)
for i in range(N):
    for j in range(N):
        D[i, j] = int(input(f"D[{i}][{j}]: "))

print("Enter elements for Matrix E:")
E = xp.zeros((N, N), dtype=int)
for i in range(N):
    for j in range(N):
        E[i, j] = int(input(f"E[{i}][{j}]: "))

# Matrix Multiplication
F = D @ E

print("\nMatrix D:")
print(D)

print("\nMatrix E:")
print(E)

print("\nMultiplication Result (D x E):")
print(F)

Enter size of vector/matrix (N):  3


Enter elements for Vector A:


A[0]:  7
A[1]:  8
A[2]:  6


Enter elements for Vector B:


B[0]:  2
B[1]:  0
B[2]:  3



Vector A: [7 8 6]
Vector B: [2 0 3]
Addition (A + B): [9 8 9]

Enter elements for Matrix D:


D[0][0]:  1
D[0][1]:  2
D[0][2]:  3
D[1][0]:  4
D[1][1]:  5
D[1][2]:  6
D[2][0]:  7
D[2][1]:  8
D[2][2]:  9


Enter elements for Matrix E:


E[0][0]:  5
E[0][1]:  4
E[0][2]:  3
E[1][0]:  2
E[1][1]:  1
E[1][2]:  7
E[2][0]:  8
E[2][1]:  6
E[2][2]:  9



Matrix D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix E:
[[5 4 3]
 [2 1 7]
 [8 6 9]]

Multiplication Result (D x E):
[[ 33  24  44]
 [ 78  57 101]
 [123  90 158]]


In [1]:
!pip install cupy-cuda11x

   ---------------------------------------- 0.0/77.0 MB ? eta -:--:--
   - -------------------------------------- 3.7/77.0 MB 21.8 MB/s eta 0:00:04
   - -------------------------------------- 3.7/77.0 MB 21.8 MB/s eta 0:00:04
   -- ------------------------------------- 5.8/77.0 MB 9.3 MB/s eta 0:00:08
   --- ------------------------------------ 6.3/77.0 MB 7.6 MB/s eta 0:00:10
   --- ------------------------------------ 6.8/77.0 MB 6.8 MB/s eta 0:00:11
   --- ------------------------------------ 7.6/77.0 MB 6.1 MB/s eta 0:00:12
   ---- ----------------------------------- 8.9/77.0 MB 6.0 MB/s eta 0:00:12
   ----- ---------------------------------- 10.0/77.0 MB 6.0 MB/s eta 0:00:12
   ----- ---------------------------------- 11.0/77.0 MB 5.6 MB/s eta 0:00:12
   ------ --------------------------------- 12.1/77.0 MB 5.6 MB/s eta 0:00:12
   ------- -------------------------------- 13.6/77.0 MB 5.7 MB/s eta 0:00:12
   ------- -------------------------------- 14.4/77.0 MB 5.5 MB/s eta 0:00:12